### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by r3nor** [DUOLabs333/service#1]
Hey, do you have any contact mail or anything like that? I know this can sound strange, but I'd like to talk with you via email. I can use [Session](https://getsession.org/) too, if you want more private chat.

Thank you.

**Comment by DUOLabs333** [comment]
I use Matrix, is that OK?

**Comment by r3nor** [comment]
Yes, that's ok for me

**Comment by DUOLabs333** [comment]
Ok, my username is @duolabs_333:matrix.org

**Comment by DUOLabs333** [comment]
Do you still want to contact me?
